name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Healthchecks.io (CI)
        run: curl -fsS --retry 2 https://hc-ping.com/06ff4b2c-9680-456e-98f0-c7c4e90abf9f/start || true

      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Trigger Webhook to Live Server
        run: |
          curl -X POST \
               -H "Authorization: Bearer ${{ secrets.DEPLOY_WEBHOOK_TOKEN }}" \
               https://blog.salucci.ch/webhook

      - name: Success ping to Healthchecks.io (CI)
        if: success()
        run: curl -fsS --retry 2 https://hc-ping.com/06ff4b2c-9680-456e-98f0-c7c4e90abf9f || true

      - name: Failure ping to Healthchecks.io (CI)
        if: failure()
        run: curl -fsS --retry 2 https://hc-ping.com/06ff4b2c-9680-456e-98f0-c7c4e90abf9f/fail || true
